server:
  port: 8090
spring:
  datasource:
    username: gniu
    password: gniu
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
