server:
  port: 8090
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gniu-ipro:3306/cloud01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
