server:
  port: 8090
spring:
  datasource:
    username: gniu
    password: '{cipher}b1f83b099368c039be8a798b5005f6fb0470a5065482266cf8ded42fcee8675a'
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  author: 'Gary Niu'
  email: 'gary.niu@gmail.com'
  
management:
  security:
    enabled: false
  endpoints:
    expose: '*'
